### ISSUE TITLE
Launch remains in the state of In-Progress when using plugins such as retryTo

### ISSUE THREAD

**Issue by nirmal-darji** [PeterNgTr/codeceptjs-rphelper#18]
I am using retryTo plugin in the test and below is the example 

```
 await retryTo(() => {
      I.waitForVisible(elementLocator);
      I.click(elementLocator);
      I.waitForInvisible(elementLocator, 25);
    }, 2);
```
So in the first go it waits for the element it clicks on it and then wait to disappear that element and waits for 25 seconds for it.
After 25 seconds if its still visible it will perform the same steps again and now it worked fine.

The issue is in the first attempt ideally it should complete the sub-step I.waitForInvisible(elementLocator, 25); after 25 seconds but it remains "In-progress" and starts with the second attempt. Since that sub-step remained "In-Progress", it also results launch to remain in the state of "In-Progress"

Can anyone please help me with that?

![ElementVisibility](https://github.com/kobenguyent/codeceptjs-rphelper/assets/96242639/b760074f-31d2-4c6a-8ff0-6e03901ea731)

**Comment by nirmal-darji** [comment]
Issue is also observed for one more plugin- tryTo()

```
async isGPKEVisible(gkpeNotification: string): Promise<boolean> {
     return await tryTo(() => I.see(gkpeNotification));
}
```

**Comment by nirmal-darji** [comment]
Hi @kobenguyent ,

Hope you are doing fine :)

Would it be possible for you to merge the open PR- https://github.com/kobenguyent/codeceptjs-rphelper/pull/19?

I am eagerly looking forward to incorporating this update into my testing workflow on the Report Portal, and your assistance in merging the PR would be greatly appreciated.

**Comment by kobenguyent** [comment]
thanks for your report! Tested with latest release, looked good! Closed this issue for now!
