### ISSUE TITLE
Random test assertEqual failure keeps test "in progress" after execution

### ISSUE THREAD

**Issue by mtrejo-evgo** [PeterNgTr/codeceptjs-rphelper#31]
The local test execution completes but on report portal the test run stays in progress with one test that looks like it didn't complete. The test completed and has a failure on a assertEqual (chai wrapper). 
When I fix the test failure, it jumps to another test failure with an assertEqual fail and keeps it "in progress".

`I.assertEqual(400, 202)`

<img width="1365" alt="Screenshot 2024-05-14 at 10 11 39 AM" src="https://github.com/kobenguyent/codeceptjs-rphelper/assets/109625371/2defd27a-ca4d-47c1-803d-7da9239d9d87">

**Comment by kobenguyent** [comment]
Hey @mtrejo-evgo may you give it a try with CodeceptJS helper https://codecept.io/helpers/Expect/ it's pretty much the same with chai expect I think.

**Comment by mtrejo-evgo** [comment]
Hey @kobenguyent, I switched to the expect helper but I still see the "in progress" issue.

**Comment by kobenguyent** [comment]
@mtrejo-evgo would you mind sharing the logs so we could look into it?

plugins: {
    reportportal: {
      require: 'codeceptjs-rphelper',
      token: 'YOUR_TOKEN',
      endpoint: 'http://localhost:8080/api/v1',
      launchName: 'This is awesome',
      launchDescription: 'This is a description of your launch',
      launchAttributes: [{ key: 'yourKey', value: 'yourValue' }],
      projectName: 'YOUR_PROJECT',
      rerun: false,
      debug: true,// set this to true
      enabled: true
    }

**Comment by mtrejo-evgo** [comment]
Hey @kobenguyent ,

here you are

`Success start item with tempId abcd {
  id: 'REDACTED',
  uniqueId: 'REDACTED'
}

Finish test item with tempId abcd {
  promiseStart: Promise {
    {
      id: 'REDACTED’,
      uniqueId: 'REDACTED'
    }
  },
  realId: 'REDACTED',
  children: [],
  finishSend: true,
  promiseFinish: Promise { <pending> },
  resolveFinish: [Function (anonymous)],
  rejectFinish: [Function (anonymous)]
}

Start test item with tempId abcd {
  startTime: 1715791210362,
  name: `❌ [STEP]: I assertContain "\\"invalid type for variable: 'input'\\" \\"Variable \\\\\\"$input\\\\\\" got invalid value { id: \\\\\\"REDACTED”`,
  type: 'STEP',
  codeRef: `As a guest user I am able to search/❌ [STEP]: I assertContain "\\"invalid type for variable: 'input'\\" \\"Variable \\\\\\"$input\\\\\\" got invalid value { id: \\\\\\"REDACTED”`,
  testCaseId: `As a guest user I am able to search/❌ [STEP]: I assertContain "\\"invalid type for variable: 'input'\\" \\"Variable \\\\\\"$input\\\\\\" got invalid value { id: \\\\\\"REDACTED”`,
  hasStats: false,
  launchUuid: 'REDACTED'
}

Finish all children for test item with tempId abcd 

Finish test item with tempId abcd { endTime: 1715791210354, status: 'passed' }`
