### ISSUE TITLE
Error when steps fails.

### ISSUE THREAD

**Issue by deepak-monotype** [PeterNgTr/codeceptjs-rphelper#6]
Hi, I was trying RP helper and it has solved previous issues. But if any step fails like grabText, waitForElement then it throws error:
(node:58113) UnhandledPromiseRejectionWarning: Error: unknown command: session/75e482313ca943bf5c17f5abe1835bee/se/log
I am not sure whether this is due to RP helper, but I noticed this only after I started using it.

One more issue: Trying to add attachment Last Seen Screenshot to non-existent step.

**Comment by PeterNgTr** [comment]
@deepak-monotype you can try my latest changes #12 , this would hopefully fix the attachment issue.

Try to install with this

```sh
npm i PeterNgTr/codeceptjs-rphelper#refactor
```

Notes: in this change, I moved this as plugin instead of helper.

**Comment by kobenguyent** [comment]
This is now officially moved to https://github.com/reportportal/agent-js-codecept.
