### ISSUE TITLE
Clicking the failed number loads blank data

### ISSUE THREAD

**Issue by deepak-monotype** [PeterNgTr/codeceptjs-rphelper#7]
Hi,

If we click Total/Passed/Failed number from launch of any execution then it opens the launch page with a message -  No results found.

But if we click launch name or 'To investigate' then we can see all data.

**Comment by PeterNgTr** [comment]
@deepak-monotype 
> ghdmitry  19 hours ago
isssue is on that level
your test cases set as Suite.
basically witin the code you should send it as type STEP  instead of TEST
don’t ask me why, it’s legacy )
we plan to rework it for v6
